# 톰캣 서버 포트 변경 & 한글 입출력 처리
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true 

# Web Application Type Setting: 스프링 MVC 기반으로 웹 어플리케이션 구축
spring:
  main:
    web-application-type: servlet

  devtools:
    livereload:
      enabled: true


  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g26405ebaad24ef_appletella_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: admin
    password: Ahffkahffk@931


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100


# Logging setting
logging:
  level:
    org.hibernate: info
    
    
#jasypt
jasypt:
  encryptor:
    password: lfdjash3928fjaofpbnwpoqnmbgfsd9238algh906hs
    key-obtention-iterations: 10000
    pool-size: 5
    algorithm: PBEWithMD5AndDES
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64